name: itkwidgets
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - pip:
    - ipywidgets>=7.1.2
    - itk>=5.0rc1
    - itkwidgets>=0.16.1
    - matplotlib
    - zstandard
    - ipywebrtc
    - bqplot
    - plotly>=3.3.0
